title: AERIE LOVE #Title

tagline: God # Christ

author: Tyler Aerie #Name

email: tyler@aerie.love #Email

description: "Aerie Love" #Document Description

keywords: "Aerie, Love, Restoration, Healing, Recovery, Truth" #HTML meta keywords

baseurl: "/" # the subpath of your site, e.g. /blog

url: "http://aerie.love" # the base hostname

theme: jekyll-theme-slate
